export const movies = [
    { name: "Inception", genre: "Science Fiction" },
    { name: "The Shawshank Redemption", genre: "Drama" },
    { name: "The Dark Knight", genre: "Action" },
    { name: "Pulp Fiction", genre: "Crime" },
    { name: "The Lord of the Rings: The Fellowship of the Ring", genre: "Fantasy" },
    { name: "Forrest Gump", genre: "Drama" },
    { name: "Avatar", genre: "Science Fiction" },
    { name: "Jurassic Park", genre: "Adventure" },
    { name: "The Matrix", genre: "Science Fiction" },
    { name: "Titanic", genre: "Romance" },
    { name: "Fight Club", genre: "Drama" },
    { name: "Star Wars: Episode IV - A New Hope", genre: "Science Fiction" },
    { name: "The Lion King", genre: "Animation" },
    { name: "Gladiator", genre: "Action" },
    { name: "The Godfather", genre: "Crime" },
    { name: "Harry Potter and the Sorcerer's Stone", genre: "Fantasy" },
    { name: "The Avengers", genre: "Action" },
    { name: "The Social Network", genre: "Drama" },
    { name: "Eternal Sunshine of the Spotless Mind", genre: "Romance" },
    { name: "Mad Max: Fury Road", genre: "Action" },
    { name: "Toy Story", genre: "Animation" },
    { name: "Interstellar", genre: "Science Fiction" },
    { name: "Jaws", genre: "Adventure" },
    { name: "Casablanca", genre: "Romance" },
    { name: "The Silence of the Lambs", genre: "Thriller" },
    { name: "Back to the Future", genre: "Science Fiction" },
    { name: "The Great Gatsby", genre: "Drama" },
    { name: "Finding Nemo", genre: "Animation" },
    { name: "Inglourious Basterds", genre: "War" },
    { name: "The Revenant", genre: "Adventure" },
    { name: "The Departed", genre: "Crime" },
    { name: "The Witch", genre: "Horror" },
    { name: "La La Land", genre: "Musical" },
    { name: "The Green Mile", genre: "Drama" },
    { name: "Memento", genre: "Thriller" },
    { name: "No Country for Old Men", genre: "Crime" },
    { name: "The Prestige", genre: "Mystery" },
    { name: "Black Swan", genre: "Drama" },
    { name: "The Hangover", genre: "Comedy" },
    { name: "Shutter Island", genre: "Mystery" },
    { name: "Gone Girl", genre: "Thriller" },
    { name: "The Grand Budapest Hotel", genre: "Comedy" },
    { name: "The Princess Bride", genre: "Adventure" },
    { name: "Coco", genre: "Animation" },
    { name: "The Wolf of Wall Street", genre: "Comedy" },
    { name: "In the Mood for Love", genre: "Romance" },
    { name: "American Beauty", genre: "Drama" },
    { name: "Fargo", genre: "Crime" },
    { name: "Spirited Away", genre: "Animation" },
    { name: "The Big Lebowski", genre: "Comedy" },
    { name: "Raiders of the Lost Ark", genre: "Adventure" },
    { name: "The Truman Show", genre: "Drama" },
    { name: "The Sixth Sense", genre: "Thriller" },
    { name: "Amélie", genre: "Romance" },
    { name: "Reservoir Dogs", genre: "Crime" },
    { name: "Pan's Labyrinth", genre: "Fantasy" },
    { name: "The Breakfast Club", genre: "Drama" },
    { name: "Moulin Rouge!", genre: "Musical" },
    { name: "The Conjuring", genre: "Horror" },
    { name: "Blade Runner 2049", genre: "Science Fiction" },
    { name: "A Beautiful Mind", genre: "Drama" },
    { name: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", genre: "Fantasy" },
    { name: "12 Years a Slave", genre: "Drama" },
    { name: "The Godfather Part II", genre: "Crime" },
    { name: "Ratatouille", genre: "Animation" },
    { name: "Silver Linings Playbook", genre: "Drama" },
    { name: "The Notebook", genre: "Romance" },
    { name: "The Martian", genre: "Science Fiction" },
    { name: "Goodfellas", genre: "Crime" },
    { name: "Catch Me If You Can", genre: "Crime" },
    { name: "The King's Speech", genre: "Drama" },
    { name: "Moonlight", genre: "Drama" },
    { name: "Django Unchained", genre: "Western" },
    { name: "Casino Royale", genre: "Action" },
    { name: "A Star Is Born", genre: "Drama" },
    { name: "Whiplash", genre: "Drama" },
    { name: "Shawshank Redemption", genre: "Drama" },
    { name: "The Hateful Eight", genre: "Mystery" },
    { name: "Annie Hall", genre: "Comedy" },
    { name: "In Bruges", genre: "Comedy" },
    { name: "Drive", genre: "Crime" },
    { name: "The Social Network", genre: "Drama" },
    { name: "The Curious Case of Benjamin Button", genre: "Fantasy" },
    { name: "The Shape of Water", genre: "Fantasy" },
    { name: "Birdman", genre: "Comedy" },
    { name: "Her", genre: "Romance" },
    { name: "A Clockwork Orange", genre: "Science Fiction" },
    { name: "The Imitation Game", genre: "Drama" }
];


